language: node_js
sudo: required
node_js:
  - "node"
before_script:
  - docker pull dmiller94/docker-eb || true
  - yarn test
notifications:
  email: false
cache:
  - node_modules
  - yarn
services:
  - mongodb
  - docker
script:
  - docker build -t dmiller94/docker-eb .
after_script:
  - docker images
before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push dmiller94/docker-eb
