language: node_js
sudo: required
node_js:
  - "node"
before_script:
  - sleep 15
cache:
  - node_modules
services:
  - mongodb
  - docker
script:
  - docker build -t docker-eb .
after_script:
  - docker images
